version: 0.2

Phases:
    install:
      commands:
         - echo installing Node14
         - apt-get install curl
         - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
         - curl -sL https://deb.nodesource.com/setup_14.x | bash -
         - apt-get install -y nodejs nodejs-legacy
    post_build:
      commands:
         - npm start
    build:
      commands:
         - echo Building app
         - npm build
         - echo Run tests
         - npm test
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist  
