version: 0.2

Phases:
    install:
      runtime-versions:
         nodejs: 14
      commands:
         - echo installing Node14
         - apt-get install curl
         - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
         - curl -sL https://deb.nodesource.com/setup_14.x | bash -
         - apt-get install -y nodejs nodejs-legacy
    build:
      commands:
         - echo Building app
         - npm run build
         - echo Run tests
         - npm test
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist  
