version: 0.2

Phases:
    install:
      commands:
         - echo installing Node14
         - sudo apt-get install curl
         - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
         - sudo apt-get install -y nodejs nodejs-legacy
    post_build:
      commands:
         - npm start
    build:
      commands:
         - echo Building app
         - npm build
         - echo Run tests
         - npm test
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist  
