version: 0.2

run-as: root

Phases:
    install:
      commands:
         - echo installing Node14
         - apt install curl
         - apt-get install -y nodejs
    post_build:
      commands:
         - npm start
    build:
      commands:
         - echo Building app
         - npm build
         - echo Run tests
         - npm test
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist  
