version: 0.2

run-as: root

Phase:
    install:
      commands:
         - echo installing Node14
         - curl -sL https://deb.nodesource.com/setup_14.x |  bash -
         - apt install -y nodejs
    post_build:
      commands:
         - npm start
    build:
      commands:
         - echo Building app
         - npm test
         - echo Run tests
         - npm run build
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist  
